INSERT INTO usuarios VALUES('wuvioqiucoseso@yahoo.com', null, 'Felipe', 'Correa', 'Cruz', 'Mexico', 'H', '1990-04-09', null);
INSERT INTO usuarios VALUES('kaawuowie@live.com', null, 'Rene', 'Flores', 'Flores', 'Mexico', 'H', '1965-06-12', null);
INSERT INTO usuarios VALUES('zuofuexudeboxe@hotmail.com', null, 'Felipe Javier', 'Cruz', 'Cantero', 'Mexico', 'H', '1967-12-01', null);
INSERT INTO usuarios VALUES('mezaequedaa@live.com', null, 'Catarina', 'Sanchez', 'Betanzos', 'Mexico', 'M', '1975-12-10', null);
INSERT INTO usuarios VALUES('qio@gmail.com', null, 'Marlene', 'Pérez', 'Portillo', 'Mexico', 'M', '1963-02-17', null);
INSERT INTO usuarios VALUES('xavi@hotmail.com', null, 'David Mariano', 'Fuentes', 'Soto', 'Mexico', 'H', '1971-04-26', null);
INSERT INTO usuarios VALUES('sirayozui@hotmail.com', null, 'Itzel', 'Cortés', 'Santiago', 'Mexico', 'M', '1977-02-25', null);
INSERT INTO usuarios VALUES('sisoacupohe@live.com', null, 'Guillermo', 'Pérez', 'Salas', 'Mexico', 'H', '1986-09-05', null);
INSERT INTO usuarios VALUES('ropibeafu@hotmail.com', null, 'Yaren Mariela', 'Amaya', 'Maldonado', 'Mexico', 'M', '1963-02-19', null);
INSERT INTO usuarios VALUES('muyiaqaaxujea@hotmail.com', null, 'Felipe Julio', 'Ramírez', 'Amaya', 'Mexico', 'H', '1962-08-06', null);
INSERT INTO usuarios VALUES('qimidoho@gmail.com', null, 'Enrique', 'Alcantara', 'Espíndola', 'Mexico', 'H', '1974-07-01', null);
INSERT INTO usuarios VALUES('doxaco@hotmail.com', null, 'Ivon Rosa', 'Pérez', 'Correa', 'Mexico', 'M', '1995-04-06', null);
INSERT INTO usuarios VALUES('wuojo@hotmail.com', null, 'Roxana Mariana', 'Robles', 'Valdez', 'Mexico', 'M', '1976-12-12', null);
INSERT INTO usuarios VALUES('mipugai@yahoo.com', null, 'Itzel Aline', 'López', 'Cantero', 'Mexico', 'M', '1966-08-07', null);
INSERT INTO usuarios VALUES('buyizi@hotmail.com', null, 'Felipe Octavio', 'Flores', 'Espada', 'Mexico', 'H', '1960-11-13', null);
INSERT INTO usuarios VALUES('gebugui@gmail.com', null, 'Ivan Miguel', 'Baez', 'Fuentes', 'Mexico', 'H', '1970-06-19', null);
INSERT INTO usuarios VALUES('peukeo@yahoo.com', null, 'Paola Ana', 'Sanchez', 'Álvarez', 'Mexico', 'M', '1971-11-20', null);
INSERT INTO usuarios VALUES('gaigiejezaica@yahoo.com', null, 'Sofia Diana', 'Correa', 'Ascencio', 'Mexico', 'M', '1978-11-06', null);
INSERT INTO usuarios VALUES('kiude@yahoo.com', null, 'Marcelo', 'Ávalos', 'Islas', 'Mexico', 'H', '1988-03-22', null);
INSERT INTO usuarios VALUES('zeasereokuzue@hotmail.com', null, 'Ricardo Juan', 'Rojas', 'Ochoa', 'Mexico', 'H', '1988-10-02', null);
INSERT INTO usuarios VALUES('gaufavu@gmail.com', null, 'Andrés Roman', 'Castillo', 'De la Rosa', 'Mexico', 'H', '1960-07-02', null);
INSERT INTO usuarios VALUES('muo@gmail.com', null, 'Ricardo Enrique', 'Regalado', 'Abrego', 'Mexico', 'H', '1980-11-04', null);
INSERT INTO usuarios VALUES('juodiaqizixi@yahoo.com', null, 'Isis', 'Ávalos', 'Ávalos', 'Mexico', 'M', '1973-02-17', null);
INSERT INTO usuarios VALUES('voaveosoero@hotmail.com', null, 'Sandra Gianelli', 'Macias', 'De la Rosa', 'Mexico', 'M', '1986-09-19', null);
INSERT INTO usuarios VALUES('mayaviciupa@gmail.com', null, 'Ximena', 'Flores', 'Flores', 'Mexico', 'M', '1986-05-07', null);
INSERT INTO usuarios VALUES('ceara@live.com', null, 'Joel', 'Castillo', 'Flores', 'Mexico', 'H', '1991-03-12', null);
INSERT INTO usuarios VALUES('xue@hotmail.com', null, 'Victor Esteban', 'Rojas', 'Robles', 'Mexico', 'H', '1974-03-22', null);
INSERT INTO usuarios VALUES('poebacuo@gmail.com', null, 'Jazmin Estefania', 'Sanchez', 'Islas', 'Mexico', 'M', '1987-09-17', null);
INSERT INTO usuarios VALUES('dewuje@gmail.com', null, 'Ivon', 'Bustos', 'Torres', 'Mexico', 'M', '1990-04-29', null);
INSERT INTO usuarios VALUES('coefaa@live.com', null, 'Vanessa Yessica', 'Pérez', 'Rivera', 'Mexico', 'M', '1980-05-12', null);
INSERT INTO usuarios VALUES('ceneayaajikege@live.com', null, 'Ángel Ángel', 'Betanzos', 'Ascencio', 'Mexico', 'H', '1983-01-25', null);
INSERT INTO usuarios VALUES('baveo@yahoo.com', null, 'Liliana', 'Espíndola', 'Beltran', 'Mexico', 'M', '1992-10-26', null);
INSERT INTO usuarios VALUES('cifa@live.com', null, 'Salvador', 'Moreno', 'Bustos', 'Mexico', 'H', '1989-01-06', null);
INSERT INTO usuarios VALUES('gezugea@live.com', null, 'Alix Dulce', 'Alcantara', 'Portillo', 'Mexico', 'M', '1987-11-11', null);
INSERT INTO usuarios VALUES('fuoleepohuomueya@gmail.com', null, 'Cuauhtemoc Oscar', 'López', 'Carrillo', 'Mexico', 'H', '1979-12-21', null);
INSERT INTO usuarios VALUES('dowaboqacu@hotmail.com', null, 'Alfonso Oscar', 'Rojas', 'Alcantara', 'Mexico', 'H', '1972-07-23', null);
INSERT INTO usuarios VALUES('qikaluili@gmail.com', null, 'Santiago', 'Abrego', 'Cruz', 'Mexico', 'H', '1967-12-01', null);
INSERT INTO usuarios VALUES('mibavaropawoi@live.com', null, 'Enrique Tomas', 'Quintana', 'Aguilar', 'Mexico', 'H', '1968-08-11', null);
INSERT INTO usuarios VALUES('woxoucaruezi@hotmail.com', null, 'Alberto Axel', 'Fernandez', 'Velasco', 'Mexico', 'H', '1982-12-24', null);
INSERT INTO usuarios VALUES('toamue@hotmail.com', null, 'Felipe', 'Ramírez', 'Pérez', 'Mexico', 'H', '1994-11-06', null);
INSERT INTO usuarios VALUES('dii@hotmail.com', null, 'Ivon Marlene', 'Soto', 'Guardado', 'Mexico', 'M', '1994-11-11', null);
INSERT INTO usuarios VALUES('bee@live.com', null, 'Oscar', 'Soto', 'Rojas', 'Mexico', 'H', '1964-09-13', null);
INSERT INTO usuarios VALUES('jaasuavau@hotmail.com', null, 'Mauricio Santiago', 'Sandoval', 'Ochoa', 'Mexico', 'H', '1994-03-30', null);
INSERT INTO usuarios VALUES('ni@hotmail.com', null, 'Octavio', 'Cruz', 'Carrillo', 'Mexico', 'H', '1978-08-05', null);
INSERT INTO usuarios VALUES('siohucodeyiu@yahoo.com', null, 'Liliana', 'Sandoval', 'Delgado', 'Mexico', 'M', '1963-04-21', null);
INSERT INTO usuarios VALUES('muce@hotmail.com', null, 'Mayra Damaris', 'Osnaya', 'Castillo', 'Mexico', 'M', '1991-07-10', null);
INSERT INTO usuarios VALUES('hou@hotmail.com', null, 'Pedro Ulises', 'Rojas', 'Islas', 'Mexico', 'H', '1993-03-28', null);
INSERT INTO usuarios VALUES('sezee@gmail.com', null, 'Juana Sara', 'López', 'De la Rosa', 'Mexico', 'M', '1964-11-26', null);
INSERT INTO usuarios VALUES('moeteihumafexua@yahoo.com', null, 'Daniel', 'Robles', 'Cruz', 'Mexico', 'H', '1963-09-04', null);
INSERT INTO usuarios VALUES('xivaluitee@hotmail.com', null, 'Adael', 'Bustos', 'Alcantara', 'Mexico', 'H', '1976-12-23', null);
INSERT INTO usuarios VALUES('ridi@yahoo.com', null, 'Joel Mariano', 'Bustos', 'Cabrera', 'Mexico', 'H', '1996-01-04', null);
INSERT INTO usuarios VALUES('foba@live.com', null, 'Carlos', 'Fernandez', 'Beltran', 'Mexico', 'H', '1964-06-13', null);
INSERT INTO usuarios VALUES('zauluucio@live.com', null, 'Victor', 'Espada', 'Navarro', 'Mexico', 'H', '1975-09-17', null);
INSERT INTO usuarios VALUES('poqiuhoigoifee@yahoo.com', null, 'Juana Guadalupe', 'Fierro', 'Díaz', 'Mexico', 'M', '1976-09-19', null);
INSERT INTO usuarios VALUES('muacoyepeekoeva@gmail.com', null, 'Paola', 'Jiménez', 'Carrillo', 'Mexico', 'M', '1969-02-04', null);
INSERT INTO usuarios VALUES('ci@yahoo.com', null, 'Viridiana', 'Cabrera', 'Alcantara', 'Mexico', 'M', '1984-08-03', null);
INSERT INTO usuarios VALUES('nea@gmail.com', null, 'Ximena Rosa', 'Prospero', 'Ramírez', 'Mexico', 'M', '1970-10-31', null);
INSERT INTO usuarios VALUES('pace@live.com', null, 'Gianelli', 'Rodríguez', 'Abrego', 'Mexico', 'M', '1985-11-26', null);
INSERT INTO usuarios VALUES('ruucajaoqaigeo@hotmail.com', null, 'Tamara', 'Álvarez', 'Sanchez', 'Mexico', 'M', '1984-11-07', null);
INSERT INTO usuarios VALUES('raaxii@yahoo.com', null, 'Enrique', 'López', 'Quintana', 'Mexico', 'H', '1965-08-21', null);
INSERT INTO usuarios VALUES('duujaokaximii@gmail.com', null, 'Ana Ximena', 'De la Rosa', 'Moreno', 'Mexico', 'M', '1963-09-17', null);
INSERT INTO usuarios VALUES('bozeibeazazi@live.com', null, 'Victor', 'Cabrera', 'Prospero', 'Mexico', 'H', '1988-10-17', null);
INSERT INTO usuarios VALUES('jojazawiixii@live.com', null, 'Ivon Marlene', 'Abrego', 'Maldonado', 'Mexico', 'M', '1978-02-18', null);
INSERT INTO usuarios VALUES('xiuroubotugee@live.com', null, 'Luis', 'Macias', 'Hernández', 'Mexico', 'H', '1966-08-07', null);
INSERT INTO usuarios VALUES('wao@gmail.com', null, 'Andrea Zoe', 'Durán', 'Osnaya', 'Mexico', 'M', '1972-05-16', null);
INSERT INTO usuarios VALUES('xuinuoloa@live.com', null, 'Valeria Mariela', 'Álvarez', 'Portillo', 'Mexico', 'M', '1986-05-04', null);
INSERT INTO usuarios VALUES('rudexu@yahoo.com', null, 'Felipe Alberto', 'Navarro', 'Fierro', 'Mexico', 'H', '1976-07-18', null);
INSERT INTO usuarios VALUES('fula@yahoo.com', null, 'Roxana', 'Soto', 'López', 'Mexico', 'M', '1979-05-26', null);
INSERT INTO usuarios VALUES('jolewunutaivu@yahoo.com', null, 'Pedro', 'Robles', 'Correa', 'Mexico', 'H', '1965-09-12', null);
INSERT INTO usuarios VALUES('yuliefoorae@hotmail.com', null, 'Diana Viridiana', 'Tello', 'Flores', 'Mexico', 'M', '1990-01-07', null);
INSERT INTO usuarios VALUES('ruqunaijeewo@hotmail.com', null, 'Joel Pedro', 'Robles', 'Quintana', 'Mexico', 'H', '1987-04-23', null);
INSERT INTO usuarios VALUES('nu@live.com', null, 'Zaira', 'Beltran', 'Maldonado', 'Mexico', 'M', '1993-08-06', null);
INSERT INTO usuarios VALUES('nua@gmail.com', null, 'Francisco', 'Jiménez', 'Velasco', 'Mexico', 'H', '1974-04-21', null);
INSERT INTO usuarios VALUES('weviaxeque@gmail.com', null, 'Sofia Mariela', 'Jiménez', 'Castillo', 'Mexico', 'M', '1993-07-21', null);
INSERT INTO usuarios VALUES('jelue@live.com', null, 'Adael Leonardo', 'Fernandez', 'Islas', 'Mexico', 'H', '1971-11-27', null);
INSERT INTO usuarios VALUES('meutoopoi@gmail.com', null, 'Hugo Rodrigo', 'Guardado', 'Delgado', 'Mexico', 'H', '1970-09-29', null);
INSERT INTO usuarios VALUES('tauwoumea@live.com', null, 'Rodrigo', 'Cortés', 'Ascencio', 'Mexico', 'H', '1964-12-19', null);
INSERT INTO usuarios VALUES('xikusupuuzoa@yahoo.com', null, 'Adrian', 'Aguilar', 'Osnaya', 'Mexico', 'H', '1971-11-06', null);
INSERT INTO usuarios VALUES('pu@hotmail.com', null, 'Daniela Isabel', 'Velasco', 'Fuentes', 'Mexico', 'M', '1995-02-22', null);
INSERT INTO usuarios VALUES('niipaqamu@live.com', null, 'David', 'Alcantara', 'Regalado', 'Mexico', 'H', '1980-08-06', null);
INSERT INTO usuarios VALUES('sisotale@live.com', null, 'Sofia', 'Flores', 'López', 'Mexico', 'M', '1981-07-17', null);
INSERT INTO usuarios VALUES('liucixeohe@gmail.com', null, 'Liliana', 'Navarro', 'Durán', 'Mexico', 'M', '1965-05-01', null);
INSERT INTO usuarios VALUES('baaqia@live.com', null, 'Juan', 'Maldonado', 'Beltran', 'Mexico', 'H', '1992-10-08', null);
INSERT INTO usuarios VALUES('niku@yahoo.com', null, 'Jesús Oscar', 'Navarro', 'Sandoval', 'Mexico', 'H', '1993-11-13', null);
INSERT INTO usuarios VALUES('seuhiicuvexayeo@hotmail.com', null, 'Fernando', 'Velasco', 'Cortés', 'Mexico', 'H', '1960-02-19', null);
INSERT INTO usuarios VALUES('jodiwacilafu@yahoo.com', null, 'Viridiana', 'Castillo', 'Moreno', 'Mexico', 'M', '1976-08-14', null);
INSERT INTO usuarios VALUES('nizoavio@live.com', null, 'Andrea', 'Amaya', 'Cortés', 'Mexico', 'M', '1993-01-09', null);
INSERT INTO usuarios VALUES('mibiocibe@live.com', null, 'Rodrigo', 'Ramírez', 'Fernandez', 'Mexico', 'H', '1982-10-16', null);
INSERT INTO usuarios VALUES('kieceizeasavae@gmail.com', null, 'Ximena Vanessa', 'Flores', 'Castillo', 'Mexico', 'M', '1961-12-01', null);
INSERT INTO usuarios VALUES('jeiqujivocuo@live.com', null, 'Sandra Maribel', 'Flores', 'Tello', 'Mexico', 'M', '1989-01-07', null);
INSERT INTO usuarios VALUES('habetapimuza@yahoo.com', null, 'Fernanda Viridiana', 'Cortés', 'Rojas', 'Mexico', 'M', '1986-04-26', null);
INSERT INTO usuarios VALUES('gu@gmail.com', null, 'Axel', 'Correa', 'Hernández', 'Mexico', 'H', '1974-01-10', null);
INSERT INTO usuarios VALUES('solauyui@yahoo.com', null, 'Israel', 'Macias', 'Salas', 'Mexico', 'H', '1966-12-14', null);
INSERT INTO usuarios VALUES('ju@gmail.com', null, 'Jazmin', 'Carrillo', 'Ávalos', 'Mexico', 'M', '1985-07-12', null);
INSERT INTO usuarios VALUES('bo@gmail.com', null, 'Angelica', 'Velasco', 'Herrera', 'Mexico', 'M', '1969-08-03', null);
INSERT INTO usuarios VALUES('dofaebiwehoo@hotmail.com', null, 'Saul Pedro', 'Velasco', 'Jiménez', 'Mexico', 'H', '1977-07-18', null);
INSERT INTO usuarios VALUES('viere@yahoo.com', null, 'Victor Alfonso', 'Guardado', 'Alcantara', 'Mexico', 'H', '1981-10-12', null);
INSERT INTO usuarios VALUES('xuqebu@hotmail.com', null, 'Ángel', 'Ramírez', 'Moreno', 'Mexico', 'H', '1988-12-17', null);
INSERT INTO usuarios VALUES('yibietoo@yahoo.com', null, 'Diana', 'Baez', 'Baez', 'Mexico', 'M', '1975-04-25', null);
INSERT INTO usuarios VALUES('savivizevifi@live.com', null, 'Alma', 'Fernandez', 'Fernandez', 'Mexico', 'M', '1969-06-15', null);
